"""Add foreign keys to attendance table

Revision ID: ff5c0d2c2080
Revises: 9b369a78ac9c
Create Date: 2026-05-01 15:04:54.079021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5c0d2c2080'
down_revision: Union[str, Sequence[str], None] = '9b369a78ac9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attendances', 'cameras', ['exit_camera_id'], ['id'])
    op.create_foreign_key(None, 'attendances', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'attendances', 'cameras', ['enter_camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    op.drop_constraint(None, 'attendances', type_='foreignkey')
    # ### end Alembic commands ###
